BASE_URL = "http://localhost:8080/index.html"

OUTER_FRAME_ID = "outerFrame"
INNER_FRAME_ID = "appFrame"

MODAL_TIMEOUT_MS = 3000
GRID_LOAD_TIMEOUT_MS = 10000
SAVE_TIMEOUT_MS = 3000

EXPECTED_ISSUE_COUNT = 10

SFID_EDIT_TARGET = "00Qak00000RHtuzEAD"
EDIT_VALUE = "123 Test Street"

SEVENTH_CARD_INDEX = 6
SEVENTH_CARD_ORIGINAL_PHONE = "778.555.6677"

FIRST_CARD_INDEX = 0
THIRD_CARD_INDEX = 2
FIFTH_CARD_INDEX = 4

SELECTION_COUNT_3 = "3 issue(s) selected"
SELECTION_COUNT_10 = "10 issue(s) selected"
